# Generated by Django 4.2.14 on 2024-11-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_articles_claps_remove_claps_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='topics',
        ),
        migrations.AddField(
            model_name='articles',
            name='topics',
            field=models.ManyToManyField(to='articles.topics'),
        ),
    ]
