# Generated by Django 4.2.14 on 2024-11-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_articles_article_rename_topics_topic'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
