# Generated by Django 4.2.14 on 2024-11-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_clap_alter_article_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='clap',
            table='clap',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
